# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Multi-alphabet-Text-Recognition',
                'doc_host': 'https://MladenDzida.github.io',
                'git_url': 'https://github.com/MladenDzida/Multi-alphabet-Text-Recognition',
                'lib_path': 'Multi_alphabet_Text_Recognition'},
  'syms': { 'Multi_alphabet_Text_Recognition.core': { 'Multi_alphabet_Text_Recognition.core.foo': ( 'core.html#foo',
                                                                                                    'Multi_alphabet_Text_Recognition/core.py')}}}
