# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/crop_words.ipynb.

# %% auto 0
__all__ = ['crop_text_from_image_korean']

# %% ../nbs/crop_words.ipynb 1
import cv2
from pathlib import Path

# %% ../nbs/crop_words.ipynb 2
# def crop_text_from_image_japanese():
#     for el in (root[1][2]):
#         if el.text:
#             print(el.text, el.attrib)
#             width = int(el.attrib['xmax']) - int(el.attrib['xmin'])
#             height = int(el.attrib['ymax']) - int(el.attrib['ymin'])
#             x = int(el.attrib['xmin'])
#             y = int(el.attrib['ymin'])
#             # Crop image to specified area using slicing
#             crop_img = img[y:y+height, x:x+width]
#             # Show image
#             cv2.imshow("cropped", crop_img)
#             cv2.waitKey(0)
            
def crop_text_from_image_korean(img_path, x, y, width, height, image_save_path):
    img = cv2.imread(img_path)
    # Crop image to specified area using slicing
    crop_img = img[y:y+height, x:x+width]
    # Show image
    cv2.imshow("cropped", crop_img)
#     cv2.waitKey(0)
    
    if not Path(image_save_path).exists():
#         cv2.imwrite(image_save_path, crop_img)
        cv2.imencode(".jpg", crop_img)[1].tofile(image_save_path)
