# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/xml_parser.ipynb.

# %% auto 0
__all__ = ['read_kaist_xml']

# %% ../nbs/xml_parser.ipynb 1
from typing import List
import xml.etree.ElementTree as ET

# %% ../nbs/xml_parser.ipynb 2
def read_kaist_xml(path: str) -> List[str]:
    try:
        tree = ET.parse(path)
        root = tree.getroot()

        all_words = []
        words_positions = []
        for word in root[0][2]:
            word_list = []
            for letter_index in range(len(word)):
                word_list.append(word[letter_index].attrib['char'])
            all_words.append(''.join(word_list))
            words_positions.append((int(word.attrib['x']), int(word.attrib['y']), int(word.attrib['width']), int(word.attrib['height'])))
        return (all_words, True, words_positions)
    except:
        return ([], False, [])
